### ISSUE TITLE
New buttons shown on "Builds" and "Pull Requests" pages

### ISSUE THREAD

**Issue by kos811** [leon737/TFS-Chrome-extensions#3]
![i109 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/5595120/25003183/e002c2dc-2056-11e7-8b55-1e21fd370a65.jpg)

![image](https://cloud.githubusercontent.com/assets/5595120/25003208/f3f068c6-2056-11e7-82d0-dc04c93a7ae3.png)

**Comment by leon737** [comment]
can be fixed with manifest.json setup
